#!/usr/bin/env python3
"""Export the tabular IDS model of xai_cost.py to C, plus reference outputs.

The model is rebuilt exactly as xai_cost.py builds it (same data generator,
split, hyper-parameters and seed), then written as flat node arrays that the
MCU firmware traverses. Reference margins and exact TreeSHAP values from the
`shap` package are exported too, so the C port is checked on the host before
any lab time is spent (host_check.c).

    ../.venv/bin/python export_model.py      # writes model.h, ref.json
"""
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from xai_cost import make_data, SEED  # noqa: E402  same generator and seed

N_TEST = 16      # samples embedded in the firmware
N_BG = 100       # background rows, as xai_cost.py --background default


def main():
    import xgboost as xgb
    import shap
    from sklearn.model_selection import train_test_split

    X, y = make_data()
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.25,
                                          stratify=y, random_state=SEED)
    model = xgb.XGBClassifier(
        n_estimators=200, max_depth=6, learning_rate=0.1,
        tree_method="hist", n_jobs=1, random_state=SEED,
        eval_metric="logloss")
    model.fit(Xtr, ytr)
    bst = model.get_booster()
    bg = shap.sample(Xtr, N_BG, random_state=SEED).astype(np.float32)

    feat, thr, left, right, val, cover, roots = [], [], [], [], [], [], []
    for tj in bst.get_dump(dump_format='json', with_stats=True):
        t = json.loads(tj)
        base = len(feat)
        # breadth-first so child indices are known; ids are XGBoost node ids
        order, q = [], [t]
        while q:
            n = q.pop(0)
            order.append(n)
            q.extend(n.get('children', []))
        pos = {n['nodeid']: base + i for i, n in enumerate(order)}
        roots.append(base)
        for n in order:
            if 'leaf' in n:
                feat.append(-1); thr.append(0.0); left.append(-1); right.append(-1)
                val.append(n['leaf'])
            else:
                # 'missing' branch ignored: the data are dense (no NaN)
                feat.append(int(n['split'][1:])); thr.append(n['split_condition'])
                left.append(pos[n['yes']]); right.append(pos[n['no']]); val.append(0.0)
            cover.append(n['cover'])
    n_nodes = len(feat)
    assert n_nodes < 32768

    margin_te = bst.predict(xgb.DMatrix(Xte[:N_TEST]), output_margin=True)
    leaf_sum = np.zeros(N_TEST)
    # base margin = XGBoost margin minus sum of leaves (read, not assumed)
    for i in range(N_TEST):
        s = 0.0
        for r in roots:
            k = r
            while feat[k] >= 0:
                k = left[k] if Xte[i, feat[k]] < np.float32(thr[k]) else right[k]
            s += val[k]
        leaf_sum[i] = s
    base = float(np.median(margin_te - leaf_sum))
    assert np.max(np.abs(margin_te - leaf_sum - base)) < 1e-4

    expl = shap.TreeExplainer(model)
    phi = expl.shap_values(Xte[:N_TEST])
    ev = float(np.atleast_1d(expl.expected_value)[0])

    f32 = lambda a: ', '.join(f'{float(v):.9e}f' for v in a)
    i16 = lambda a: ', '.join(str(int(v)) for v in a)
    with open(HERE / 'model.h', 'w') as f:
        f.write('/* Generated by export_model.py -- do not edit. */\n')
        f.write('#ifndef XAI_MODEL_H\n#define XAI_MODEL_H\n#include <stdint.h>\n')
        f.write(f'#define N_FEAT {X.shape[1]}\n#define N_TREES {len(roots)}\n')
        f.write(f'#define N_NODES {n_nodes}\n#define N_TEST {N_TEST}\n#define N_BG {N_BG}\n')
        f.write(f'#define BASE_MARGIN {base:.9e}f\n')
        f.write(f'static const int16_t node_feat[N_NODES] = {{{i16(feat)}}};\n')
        f.write(f'static const float node_thr[N_NODES] = {{{f32(thr)}}};\n')
        f.write(f'static const int16_t node_left[N_NODES] = {{{i16(left)}}};\n')
        f.write(f'static const int16_t node_right[N_NODES] = {{{i16(right)}}};\n')
        f.write(f'static const float node_val[N_NODES] = {{{f32(val)}}};\n')
        f.write(f'static const float node_cover[N_NODES] = {{{f32(cover)}}};\n')
        f.write(f'static const int16_t tree_root[N_TREES] = {{{i16(roots)}}};\n')
        f.write(f'static const float test_x[N_TEST][N_FEAT] = {{'
                + ', '.join('{' + f32(r) + '}' for r in Xte[:N_TEST]) + '};\n')
        f.write(f'static const float bg_x[N_BG][N_FEAT] = {{'
                + ', '.join('{' + f32(r) + '}' for r in bg) + '};\n')
        f.write('#endif\n')
    json.dump({'n_nodes': n_nodes, 'n_trees': len(roots), 'base_margin': base,
               'expected_value': ev, 'margin': margin_te.tolist(),
               'phi': np.asarray(phi).tolist()},
              open(HERE / 'ref.json', 'w'))
    print(f'nodes={n_nodes} trees={len(roots)} base={base:.6f} ev={ev:.6f}')


if __name__ == '__main__':
    main()
